export const desk = [
    {
        id: 1,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Abdrshin Ramil Khayrullayevich",
        description: "During the crossing of the Dnieper, the platoon commanded by Sergeant Abdrshin was the first to occupy the defense and ensured the successful crossing of all other units to the other side.",
        DateAndPlaceOfBirth: ["11.01.1925", "Novomusino, Sharlyksky District, Orenburg Oblast"],
        DateAndPlaceOfDepartureOrDeath: ["11.08.1943", "Zarubintsy Village, Kanevsky District, Cherkasy Oblast, Ukraine"],
        MilitarySpecialty: "Sergeant, squad commander of the 1st motorized rifle battalion of the 69th mechanized brigade",
        MilitaryRankAndJobTitle: "1st Motorized Rifle Battalion, 69th Mechanized Brigade, 9th Mechanized Corps, 3rd Guards Tank Army",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated November 17, 1943, for exemplary performance of combat missions of the command at the front against the German fascist invaders and for the courage and heroism displayed during this, he was posthumously awarded the title of Hero of the Soviet Union."],
        Biography: "Born in November 1925 in the village of Novomusino, Sharlyksky District, Orenburg Oblast, Russia. Graduated from ten grades, and in July 1942, he graduated with honors from the Katakurgan Pedagogical School.",
        HeroFeat: "On the night of September 22, 1943, he was the first to cross the Dnieper. In the battle for Zarubintsy, during the attack, he and his squad were the first to storm the village and destroyed up to 10 German soldiers.",
        Awards: "Awarded the Order of Lenin and the medal 'Gold Star.'"
    },
    {
        id: 2,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Ivanov Ivan Ivanovich",
        description: "Distinguished himself in battles for the liberation of Belarus, personally destroying several enemy tanks.",
        DateAndPlaceOfBirth: ["15.05.1920", "Minsk, Belarus"],
        DateAndPlaceOfDepartureOrDeath: ["12.07.1944", "Minsk, Belarus"],
        MilitarySpecialty: "Tank platoon commander",
        MilitaryRankAndJobTitle: "Tank Brigade, 1st Belarusian Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated July 20, 1944."],
        Biography: "Born in Minsk, graduated from tank school. Participated in battles from the first days of the war.",
        HeroFeat: "During Operation Bagration, he personally destroyed 5 enemy tanks.",
        Awards: "Awarded the Order of the Red Banner."
    },
    {
        id: 3,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Petrov Petr Petrovich",
        description: "Commander of an artillery crew, distinguished himself in battles near Stalingrad.",
        DateAndPlaceOfBirth: ["10.03.1918", "Stalingrad, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["02.02.1943", "Stalingrad, USSR"],
        MilitarySpecialty: "Artillery crew commander",
        MilitaryRankAndJobTitle: "62nd Army, Stalingrad Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated February 5, 1943."],
        Biography: "Born in Stalingrad, dreamed of becoming a soldier since childhood.",
        HeroFeat: "During the Battle of Stalingrad, he destroyed several enemy tanks and infantry units.",
        Awards: "Awarded the Order of the Patriotic War I class."
    },
    {
        id: 4,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Sidorov Sidor Sidorovich",
        description: "Fighter pilot who shot down more than 20 enemy aircraft.",
        DateAndPlaceOfBirth: ["22.06.1919", "Moscow, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["15.08.1943", "Kursk Bulge, USSR"],
        MilitarySpecialty: "Fighter pilot",
        MilitaryRankAndJobTitle: "16th Air Army, 1st Belarusian Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated August 20, 1943."],
        Biography: "Born in Moscow, graduated from flight school. Participated in air battles from the first days of the war.",
        HeroFeat: "During the Kursk battle, he shot down 5 enemy planes in one day.",
        Awards: "Awarded the Order of the Red Star."
    },
    {
        id: 5,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Kuznetsov Alexey Vasilyevich",
        description: "Saprer who defused over 100 mines during the war.",
        DateAndPlaceOfBirth: ["05.09.1922", "Leningrad, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["27.01.1944", "Leningrad, USSR"],
        MilitarySpecialty: "Saprer",
        MilitaryRankAndJobTitle: "67th Army, Leningrad Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated January 30, 1944."],
        Biography: "Born in Leningrad, developed an interest in technology from childhood.",
        HeroFeat: "During the breakthrough of the Leningrad blockade, he defused more than 50 mines in one day.",
        Awards: "Awarded the Medal for Courage."
    },
    {
        id: 6,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Smirnov Alexander Nikolaevich",
        description: "Medic who saved more than 200 wounded soldiers.",
        DateAndPlaceOfBirth: ["12.04.1921", "Kiev, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["06.11.1943", "Kiev, USSR"],
        MilitarySpecialty: "Military doctor",
        MilitaryRankAndJobTitle: "38th Army, 1st Ukrainian Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated November 10, 1943."],
        Biography: "Born in Kiev, graduated from medical school.",
        HeroFeat: "During the battles for Kiev, saved over 50 wounded soldiers in one day.",
        Awards: "Awarded the Red Cross Order."
    },
    {
        id: 7,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Vasiliev Vasily Vasilievich",
        description: "Scout who obtained valuable information about enemy forces.",
        DateAndPlaceOfBirth: ["18.07.1923", "Odessa, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["10.04.1944", "Odessa, USSR"],
        MilitarySpecialty: "Scout",
        MilitaryRankAndJobTitle: "3rd Ukrainian Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated April 15, 1944."],
        Biography: "Born in Odessa, dreamed of becoming a scout since childhood.",
        HeroFeat: "During the liberation of Odessa, he acquired valuable information about enemy forces.",
        Awards: "Awarded the Order of Glory."
    },
    {
        id: 8,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Nikolaev Nikolai Nikolaevich",
        description: "Commander of a partisan detachment that destroyed several enemy trains.",
        DateAndPlaceOfBirth: ["25.12.1917", "Minsk, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["03.07.1944", "Belarus"],
        MilitarySpecialty: "Commander of the partisan detachment",
        MilitaryRankAndJobTitle: "Partisan detachment 'For the Motherland'",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated July 10, 1944."],
        Biography: "Born in Minsk, organized a partisan detachment from the first days of the war.",
        HeroFeat: "During Operation Rail War, destroyed several enemy trains.",
        Awards: "Awarded the Order of Lenin."
    },
    {
        id: 9,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Mikhailov Mikhail Mikhailovich",
        description: "Artilleryman distinguished in battles for Berlin.",
        DateAndPlaceOfBirth: ["30.10.1924", "Moscow, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["02.05.1945", "Berlin, Germany"],
        MilitarySpecialty: "Artillery gun commander",
        MilitaryRankAndJobTitle: "8th Guards Army, 1st Belarusian Front",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated May 10, 1945."],
        Biography: "Born in Moscow, graduated from artillery school.",
        HeroFeat: "During the assault on Berlin, destroyed several enemy firing points.",
        Awards: "Awarded the Order of the Red Banner."
    },
    {
        id: 10,
        image: "https://i.pinimg.com/originals/de/9a/09/de9a09644647ca86603af6c73bb542a7.jpg",
        name: "Alekseev Alexey Alekseevich",
        description: "Sailor who participated in the defense of Sevastopol.",
        DateAndPlaceOfBirth: ["14.02.1920", "Sevastopol, USSR"],
        DateAndPlaceOfDepartureOrDeath: ["09.05.1944", "Sevastopol, USSR"],
        MilitarySpecialty: "Seaman",
        MilitaryRankAndJobTitle: "Black Sea Fleet",
        TitleAndDocumentAssignment: ["Hero of the Soviet Union", "By the decree of the Presidium of the Supreme Soviet of the USSR dated May 15, 1944."],
        Biography: "Born in Sevastopol, dreamed of becoming a sailor since childhood.",
        HeroFeat: "During the defense of Sevastopol, participated in repelling several attacks from the enemy.",
        Awards: "Awarded the Medal for the Defense of Sevastopol."
    },
];